version: '3.9'

secrets:
  tg_token:
    file: ./secret/tg_token

services:
  ti4bot:
    container_name: ti4bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    secrets:
      - tg_token

#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     volumes: 
#       - cache:/data
      
# volumes:
#   cache: data/redis